# docker compose v2 (el campo 'version' es opcional en Spec actual)
# Docs: Compose v2 y startup order/healthcheck
# - https://docs.docker.com/compose/releases/migrate/
# - https://docs.docker.com/compose/how-tos/startup-order/
name: ccvi-visa-emisor

services:
  db:
    image: postgres:16
    container_name: ccvi_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: ccvi
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      # pg_isready viene en la imagen oficial de postgres
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 3s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ccvi_api
    depends_on:
      db:
        condition: service_healthy # espera a que pase el healthcheck
    ports:
      - '${PORT:-3000}:3000'
    environment:
      # URL que la API usará para conectarse a la DB dentro de la red de Compose
      DATABASE_URL: 'postgres://app:app@db:5432/ccvi'
      NODE_ENV: 'development'
      API_KEY: '${API_KEY:-dev-key}'
      PORT: '3000'

volumes:
  pg_data:
