name: Bug
description: Reportar un problema
labels: ['bug']
body:
  - type: input
    id: resumen
    attributes:
      label: Resumen
      placeholder: 'Qué ocurrió…'
    validations:
      required: true
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      placeholder: '1) ... 2) ... 3) ...'
    validations:
      required: true
