name: ci

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          check-latest: true
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - run: npm test
