# .github/workflows/ci.yml
name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {} # ← permite ejecutarlo desde la pestaña Actions

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          check-latest: true
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - name: Prepare .env for tests
        run: |
          cp .env.example .env
      - run: npm test
      - name: Build API image
        run: docker build -t ccvi-visa-emisor:ci .
